config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users
  root to: 'pages#home'

  resources :items do
    resources :listings, only: %i[new create]
    resources :transactions

  end

  resources :listings, only: %i[ index show edit update destroy]



  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :friend_requests, only: [:index, :create, :destroy]

  resources :chats, only: [:index, :create, :show] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: %i[show index] do
    resources :wallets, only: %i[new create]
  end

  resources :wallets, only: %i[edit update destroy]


  resources :reviews do
    resources :users_reviews
    resources :items_reviews
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) {
    where("chats.sender_id = ? OR chats.recipient_id = ?", user.id, user.id)
  }

  scope :between, -> (user_A, user_B) {
    where("(chats.sender_id = ? AND chats.recipient_id = ?) OR (chats.sender_id = ? AND chats.recipient_id = ?)", user_A, user_B, user_B, user_A)
  }
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord

  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship, unless: :has_inverse_relationship?
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  private

  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  def has_inverse_relationship?
    self.class.exists?(inverse_friendship_options)
  end

  def inverse_friendship_options
    { friend_id: user_id, user_id: friend_id }
  end

end

app/models/item.rb
class Item < ApplicationRecord
  attr_accessor :new_category_name
  belongs_to :user
  belongs_to :category, required: false
  has_many :listings, dependent: :destroy
  before_save :create_category_from_name

  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end
end

app/models/items_review.rb
class ItemsReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :item, dependent: :destroy
  belongs_to :time_unit, required: false
  belongs_to :listing_type, required: false
end

app/models/listing_type.rb
class ListingType < ApplicationRecord
  has_many :listings
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat


  validates_presence_of :body, :chat_id, :user_id

  def message_time
    created_at.strftime("%H:%M - %d/%b/%Y")
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :item
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/time_unit.rb
class TimeUnit < ApplicationRecord
  has_many :listings
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :items, dependent: :destroy
  has_many :listings, through: :items
  has_many :reviews, dependent: :destroy
  has_many :transactions


  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/models/users_review.rb
class UsersReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chats = Chat.involving(current_user)
  end

  def show
    @chat = Chat.find(params[:id])
    @other_user = current_user == @chat.sender ? @chat.recipient : @chat.sender
    @messages = @chat.messages.order(created_at: :asc).last(20)
    @message = Message.new
  end

  def create
    @chat = Chat.between(params[:sender_id], params[:recipient_id]).first_or_create!(chat_params)
    puts " chat created"
    redirect_to @chat
  end

  private

  def chat_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end



  def new
    @item = Item.new
  end

  def create
    ## TO DO: when categories is created and tags add it to params
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
  end

  def update
    if @item.update
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])

  end

  def item_params
    params.require(:item).permit(:description, :location, :title, :category_id, :new_category_name)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_user!, only: [:index, :show]


  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @item = Item.find(params[:item_id])


  end

  # GET /listings/1/edit
  def edit

  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.item_id = params[:item_id]

    if @listing.save!
      redirect_to listing_path(@listing)

    else
      redirect_to root_path
      #render :new


    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update

    if @listing.update(listing_params)
      redirect_to listing_path(@listing)
    else
      render :edit

    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    redirect_to listings_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def listing_params
    params.require(:listing).permit(:title, :item_id, :is_available, :sale_price, :price_per_time, :time_unit_id, :listing_type_id, :auction_begin_price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :item %>
    <%= f.input :is_available %>
    <%= f.input :sale_price %>
    <%= f.input :price_per_time %>
    <%= f.association :time_unit %>
    <%= f.association :listing_type %>
    <%= f.input :auction_begin_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/_formedit.html.erb
<%= simple_form_for @listing do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :title %>

    <%= f.input :is_available %>

    <%= f.input :sale_price %>
    <%= f.input :price_per_time %>
     <%#= f.input :time_unit_id %>
    <%#= f.input :listing_type_id %>
    <%= f.collection_select :time_unit_id, TimeUnit.all, :id, :name, :prompt => "Select a Time Unit" %>

    <%= f.collection_select :listing_type_id, ListingType.all, :id, :name, :prompt => "Select a Listing Type" %>
    <%= f.input :auction_begin_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'formedit', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
  <p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Is available</th>
      <th>Sale price</th>
      <th>Price per time</th>
      <th>Time unit</th>
      <th>Listing type</th>
      <th>Auction begin price</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.item.title %></td>
        <td><%= listing.is_available %></td>
        <td><%= listing.sale_price %></td>
        <td><%= listing.price_per_time %></td>
        <td><%= listing.time_unit.name %></td>
        <td><%= listing.listing_type.name %></td>
        <td><%= listing.auction_begin_price %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Listing',  new_item_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listing:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Item:</strong>
  <%= @listing.item.title %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @listing.is_available %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @listing.sale_price %>
</p>

<p>
  <strong>Price per time:</strong>
  <%= @listing.price_per_time %>
</p>

<p>
  <strong>Time unit:</strong>
  <%= @listing.time_unit.name %>

<p>
  <strong>Listing type:</strong>
  <%= @listing.listing_type.name %>
</p>

<p>
  <strong>Auction begin price:</strong>
  <%= @listing.auction_begin_price %>
</p>

<%#= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>