config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users
  root to: 'pages#home'

  resources :items do
    resources :listings, only: %i[new create]
    resources :transactions

  end

  resources :listings, only: %i[ index show edit update destroy]



  resources :users, only: [:index] do
    member do
      post :follow
      post :unfollow
    end
  end
  resources :friend_requests, only: [:index, :create, :destroy]

  resources :chats, only: [:index, :create, :show] do
    resources :messages, only: [:index, :create]
  end

  resources :users, only: %i[show index] do
    resources :wallets, only: %i[new create]
  end

  resources :wallets, only: %i[edit update destroy]


  resources :reviews do
    resources :users_reviews
    resources :items_reviews
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :involving, -> (user) {
    where("chats.sender_id = ? OR chats.recipient_id = ?", user.id, user.id)
  }

  scope :between, -> (user_A, user_B) {
    where("(chats.sender_id = ? AND chats.recipient_id = ?) OR (chats.sender_id = ? AND chats.recipient_id = ?)", user_A, user_B, user_B, user_A)
  }
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord

  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship, unless: :has_inverse_relationship?
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  private

  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  def has_inverse_relationship?
    self.class.exists?(inverse_friendship_options)
  end

  def inverse_friendship_options
    { friend_id: user_id, user_id: friend_id }
  end

end

app/models/item.rb
class Item < ApplicationRecord
  attr_accessor :new_category_name
  belongs_to :user
  belongs_to :category, required: false
  has_many :listings, dependent: :destroy
  before_save :create_category_from_name

  def create_category_from_name
    create_category(name: new_category_name) unless new_category_name.blank?
  end
end

app/models/items_review.rb
class ItemsReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :item, dependent: :destroy
  belongs_to :time_unit, required: false
  belongs_to :listing_type, required: false
end

app/models/listing_type.rb
class ListingType < ApplicationRecord
  has_many :listings
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat


  validates_presence_of :body, :chat_id, :user_id

  def message_time
    created_at.strftime("%H:%M - %d/%b/%Y")
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :item
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/time_unit.rb
class TimeUnit < ApplicationRecord
  has_many :listings
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :items, dependent: :destroy
  has_many :listings, through: :items
  has_many :reviews, dependent: :destroy
  has_many :transactions


  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  def is_following?(user_id)
    relationship = Follow.find_by(follower_id: id, following_id: user_id)
    return true if relationship
  end
end

app/models/users_review.rb
class UsersReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chats = Chat.involving(current_user)
  end

  def show
    @chat = Chat.find(params[:id])
    @other_user = current_user == @chat.sender ? @chat.recipient : @chat.sender
    @messages = @chat.messages.order(created_at: :asc).last(20)
    @message = Message.new
  end

  def create
    @chat = Chat.between(params[:sender_id], params[:recipient_id]).first_or_create!(chat_params)
    puts " chat created"
    redirect_to @chat
  end

  private

  def chat_params
    params.permit(:sender_id, :recipient_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end



  def new
    @item = Item.new
  end

  def create
    ## TO DO: when categories is created and tags add it to params
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])

  end

  def edit
  end

  def update
    if @item.update
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])

  end

  def item_params
    params.require(:item).permit(:description, :location, :title, :category_id, :new_category_name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_chat.html.erb
<% other_user = current_user.id = chat.sender_id ? chat.recipient : chat.sender %>
<%= link_to chat do %>
  <div class="row chat">
    <% if chat.messages.any? %>
      <div class="col-md-4">
        <%= other_user.email %>

        <%= chat.messages.last.message_time %>
      </div>
      <div class="col-md-8">
        <%= chat.messages.last.body %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/chats/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">Your Chats</div>
      <div class="panel-body">
        <div class="container">
          <%= render @chats %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chats/show.html.erb
<div style="margin-top: 30px; height: calc(100vh - 130px);">
  <div class="chat">
    <div class="messages">
      <div class="messages--content">
        <%= render @messages %>
        <%#= render 'appointments/suggestion', chat: @chat, appointment: Appointment.new %>
        <%#= render 'appointments/request', appointment: @requests.last if @requests.any? %>
      </div>
    </div>
    <div class="chat--form">
      <%= form_for [@chat, @message] do |f| %>
        <div class="message-form">
          <%= f.text_field :body, placeholder: "Type message", autofocus: true, class: "message-form--input" %>
          <%= f.hidden_field :chat_id, value: @chat.id %>
          <%= f.submit "Send", class: "message-form--submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
   <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <p>
    <label for="item_category_id">Category:</label><br />
    <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => "Select a Category" %>
    or create one:
    <%= f.text_field :new_category_name %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/index.html.erb
<ul>
  <% @items.each do |item|   %>
  <li><%= item.user_id %></li>
  <li><%= item.title %></li>

  <li><%= item.description %></li>
  <li><%= item.location %></li>
  <li><%= item.category.name %></li>

  <%= link_to 'show', item_path(item) %>





  <% end %>

  <%= link_to 'New item', new_item_path %>

  </ul>

app/views/items/new.html.erb
<!--

<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title,
        required: true,
        autofocus: true,
        input_html: { autocomplete: "title" }%>

         <%= f.input :description,
        required: true,
        autofocus: true,
        input_html: { autocomplete: "description" }%>

         <%= f.input :location,
        required: true,

        autofocus: true,
        input_html: { autocomplete: "location" }%>

  </div>

  <div class="form-actions">
    <%= f.button :submit , class: "btn btn-primary" %>
  </div>
  <br>
  <div><%= link_to 'Back', items_path, class: "btn btn-dark" %></div>
<% end %>
 -->

 <h1>New item</h1>
<%= render 'form', item: @item %>
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<ul>
  <li><%= @item.id  %></li>

  <li><%= @item.title  %></li>

  <li><%= @item.user_id %></li>
  <li><%= @item.description %></li>
  <li><%= @item.location %></li>
  <li><%= @item.category.name %></li>
  <%= link_to 'creat listing',  new_item_listing_path(@item) %>


</ul>